BEGIN TRANSACTION;

--UPDATE Products SET ProductName = 'Pedro';  

--DELETE FROM Products WHERE 0;
UPDATE Products SET ProductName = 'Chais' WHERE ProductName = 'Tazon';


COMMIT -- ACEPTAMOS EL CAMBIO EFECTUADO POR TRANSACTION
ROLLBACK  -- SE REGRESA A LA NORMALIDAD ANTES DE UNA TRANSACTION